const Sdata = {
    shopItems: [
      {
        id: 7,
        cover: "./images/shops/cover1.webp",
        name: "Frok",
        price: "180",
        discount: "25",
      },
      {
        id: 8,
        cover: "./images/shops/cover2.jpg",
        name: "Yellow fork",
        price: "120",
        discount: "10",
      },
      {
        id: 9,
        cover: "./images/shops/cover3.jpg",
        name: "Toy",
        price: "20",
        discount: "50 ",
      },
      {
        id: 10,
        cover: "./images/shops/cover4.png",
        name: "pant",
        price: "199",
        discount: "10 ",
      },
      {
        id: 11,
        cover: "./images/shops/cover5.png",
        name: "Cotton Frok",
        price: "480",
        discount: "20 ",
      },
      {
        id: 12,
        cover: "./images/shops/cover6.png",
        name: "Shoes",
        price: "400",
        discount: "20 ",
      },
      {
        id: 13,
        cover: "./images/shops/cover8.jpg",
        name: "Nigth dress",
        price: "360",
        discount: "5 ",
      },
      {
        id: 14,
        cover: "./images/shops/coverg1.jpg",
        name: "Cotton Night Dress",
        price: "180",
        discount: "10",
      },
      {
        id: 15,
        cover: "./images/shops/coverg3.jpg",
        name: "yellow baby dress",
        price: "5",
        discount: "20",
      },
      {
        id: 16,
        cover: "./images/shops/coverg4.jpg",
        name: "Shoes",
        price: "250",
        discount: "20",
      },
      {
        id: 17,
        cover: "./images/shops/coverg5.jpg",
        name: "Hoody",
        price: "500",
        discount: "13",
      },
      {
        id: 18,
        cover: "./images/shops/coverg6.jpg",
        name: "pant Shirt",
        price: "5",
        discount: "2",
      },
      {
        id: 19,
        cover: "./images/shops/coverg3.jpg",
        name: "Silver Cap",
        price: "250",
        discount: "10",
      },
      {
        id: 20,
        cover: "./images/shops/coverg7.jpg",
        name: "Frok",
        price: "300",
        discount: "12",
      },
      {
        id: 21,
        cover: "./images/shops/cover7.jpg",
        name: "Sun glasses",
        price: "300",
        discount: "12",
      },
      {
        id: 22,
        cover: "./images/shops/download.jpg",
        name: "Cool T-Shirt",
        price: "300",
        discount: "12",
      },
      {
        id: 23,
        cover: "./images/shops/covergg3.jpg",
        name: "Red Frok",
        price: "300",
        discount: "12",
      },
      {
        id: 24,
        cover: "./images/shops/OIP.jpg",
        name: "multi-color Frok",
        price: "300",
        discount: "12",
      },
     {
    id:31,
    cover: "https://m.media-amazon.com/images/I/91WDOXmC9IL._UL1500_.jpg",
    name: "Nylon Jeans",
    discount: "30",
    prevPrice: "$140,00",
    price: "200",
    company: "gucci",
    category: "Jeans",
  },
  {
    id:32,
    cover: "./images/shops/cover2.jpg",
    name: "Frok",
     
    discount: "45",
    prevPrice: "$140,00",
    price: "200",
    company: "Frok",
    color: "black",
    category: "Allen Solly",
  },
  {
    id:33,
    cover: "https://m.media-amazon.com/images/I/71dliI0Kf7L._AC_UL600_FMwebp_QL65_.jpg",
    name: "Nylon Jeans",
    discount: "30",
    prevPrice: "$140,00",
    price: "200",
    company: "gucci",
    category: "Jeans",
  },

  {
    id:34,
    cover: "https://m.media-amazon.com/images/I/61HGW82EsYS._AC_UL600_FMwebp_QL65_.jpg",
    name: "Nylon Jeans",
    discount: "30",
    prevPrice: "$140,00",
    price: "200",
    company: "Being Human",
    category: "Jeans",
  },
  {
    id:35,
    cover: "./images/shops/cover1.webp",
    name: "Frok",
     
    discount: "45",
    prevPrice: "$140,00",
    price: "200",
    company: "Frok",
    color: "black",
    category: "Being Human",
  },
  {
    id:36,
    cover: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    name: "Flat Slip On Pumps",
     
    discount: "40",
    prevPrice: "$140,00",
    price: "200",
    company: "Allen Solly",
    color: "green",
    category: "Shoes",
  },
  {
    id:37,
    cover: "https://m.media-amazon.com/images/I/91WDOXmC9IL._UL1500_.jpg",
    name: "Nylon Jeans",
    discount: "30",
    prevPrice: "$140,00",
    price: "200",
    company: "gucci",
    category: "Jeans",
  },
  {
    id:38,
    cover: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    name: "Knit Ballet Flat",
     
    discount: "40",
    prevPrice: "$140,00",
    price: "50",
    company: "Gucci",
    color: "black",
    category: "Shoes",
  },

  {
    id:39,
    cover: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    name: "Loafer Flats",
     
    discount: "40",
    prevPrice: "$140,00",
    price: "50",
    company: "Being Human",
    color: "white",
    category: "Shoes",
  },
  {
    id:40,
    cover: "https://m.media-amazon.com/images/I/9198yAcm9oL._AC_UL600_FMwebp_QL65_.jpg",
    name: "Nylon Jeans",
    discount: "35",
    prevPrice: "$140,00",
    price: "200",
    company: "gucci",
    category: "Jeans",
  },
  { id:41,
    cover: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    name: "Nike Zoom Freak",
     
    discount: "40",
    prevPrice: "$140,00",
    price: "200",
    company: "gucci",
    color: "green",
    category: "Shoes",
  },
  {
    id:42,
    cover: "./images/shops/OIP.jpg",
    name: "Multi color Frok",
     
    discount: "45",
    prevPrice: "$140,00",
    price: "200",
    company: "Frok",
    color: "black",
    category: "Allen Solly",
  },
  {
    id:43,
    cover: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    name: "Nike Men's Sneaker",
     
    discount: "20",
    prevPrice: "$140,00",
    price: "200",
    company: "Allen solly",
    color: "blue",
    category: "Shoes",
  },
  
  {
    id:44,
    cover: "https://images-eu.ssl-images-amazon.com/images/I/81yNWxYnGaL._AC_UL160_SR160,160_.jpg",
    name: "Nylon Jeans",
    discount: "30",
    prevPrice: "$140,00",
    price: "200",
    company: "Being Human",
    category: "Jeans",
  },

]
 }
  export default Sdata
  