const Sdata = {
  shopItems: [
    {
      id: 7,
      cover: "./images/shops/img1.webp",
      name: "Frok",
      price: "180",
      discount: "25",
    },
    {
      id: 8,
      cover: "./images/shops/img2.jpg",
      name: "Yellow fork",
      price: "120",
      discount: "10",
    },
    {
      id: 9,
      cover: "./images/shops/img3.jpg",
      name: "Toy",
      price: "20",
      discount: "50 ",
    },
    {
      id: 10,
      cover: "./images/shops/img4.png",
      name: "pant",
      price: "199",
      discount: "10 ",
    },
    {
      id: 11,
      cover: "./images/shops/img5.png",
      name: "Cotton Frok",
      price: "480",
      discount: "20 ",
    },
    {
      id: 12,
      cover: "./images/shops/img6.png",
      name: "Shoes",
      price: "400",
      discount: "20 ",
    },
    {
      id: 13,
      cover: "./images/shops/img8.jpg",
      name: "Nigth dress",
      price: "360",
      discount: "5 ",
    },
    {
      id: 14,
      cover: "./images/shops/imgg1.jpg",
      name: "Cotton Night Dress",
      price: "180",
      discount: "10",
    },
    {
      id: 15,
      cover: "./images/shops/imgg3.jpg",
      name: "yellow baby dress",
      price: "5",
      discount: "20",
    },
    {
      id: 16,
      cover: "./images/shops/imgg4.jpg",
      name: "Shoes",
      price: "250",
      discount: "20",
    },
    {
      id: 17,
      cover: "./images/shops/imgg5.jpg",
      name: "Hoody",
      price: "500",
      discount: "13",
    },
    {
      id: 18,
      cover: "./images/shops/imgg6.jpg",
      name: "pant Shirt",
      price: "5",
      discount: "2",
    },
    {
      id: 19,
      cover: "./images/shops/imgg3.jpg",
      name: "Shoes",
      price: "250",
      discount: "10",
    },
    {
      id: 20,
      cover: "./images/shops/imgg7.jpg",
      name: "Frok",
      price: "300",
      discount: "12",
    },
    {
      id: 21,
      cover: "./images/shops/img7.jpg",
      name: "Sun glasses",
      price: "300",
      discount: "12",
    },
    {
      id: 22,
      cover: "./images/shops/download.jpg",
      name: "Cool T-Shirt",
      price: "300",
      discount: "12",
    },
    {
      id: 23,
      cover: "./images/shops/imggg3.jpg",
      name: "Red Frok",
      price: "300",
      discount: "12",
    },
    {
      id: 24,
      cover: "./images/shops/OIP.jpg",
      name: "multi-color Frok",
      price: "300",
      discount: "12",
    },
    
  ],
}
export default Sdata
